# 01. Tìm Hiểu Dữ Liệu và Tiền Xử Lý Dữ Liệu
**Học phần:** Khai thác dữ liệu - Nhóm 12  
**Đề tài 16:** Phân nhóm quốc gia theo các yếu tố tạo nên mức độ hạnh phúc (World Happiness Report)  
---
### Đối chiếu với Mục 1.2 - Pipeline bắt buộc của đồ án:
- [x] **Bước 1:** Xác định bài toán và câu hỏi khai thác dữ liệu.
- [x] **Bước 2:** Tìm hiểu dữ liệu (nguồn gốc, ý nghĩa biến, đơn vị đo, ghép 5 năm).
- [x] **Bước 3:** Đánh giá chất lượng dữ liệu (giá trị thiếu, trùng lặp, tính nhất quán schema).
- [x] **Bước 4 (Phần 1):** Tiền xử lý dữ liệu (chuẩn hóa tên cột, xử lý missing, hợp nhất dữ liệu).

## [Bước 1/11] Xác định bài toán và câu hỏi khai thác dữ liệu
1. **Bối cảnh & Mục tiêu:**
   - Đề tài tập trung vào bài toán **Gom cụm (Clustering / Unsupervised Learning)** để phân nhóm các quốc gia trên thế giới.
   - Mục tiêu: Phát hiện các hình thái phân hóa chất lượng sống dựa trên 6 yếu tố cơ sở (GDP, Hỗ trợ xã hội, Sức khỏe/Tuổi thọ, Quyền tự do, Sự hào phóng, Nhận thức tham nhũng).
2. **Câu hỏi khai thác dữ liệu cụ thể:**
   - Có thể phân chia các quốc gia trên thế giới thành những nhóm (cụm) đặc trưng nào?
   - Các nhóm quốc gia khác biệt rõ rệt nhất ở những yếu tố nào (ví dụ: kinh tế vs thể chế xã hội)?
   - Nhóm quốc gia nào ở tình trạng báo động và cần sự hỗ trợ/viện trợ quốc tế?
3. **Quy tắc vàng (Bắt buộc theo hướng dẫn đề tài 16):**
   - Tuyệt đối **KHÔNG** đưa thuộc tính `happiness_score` hoặc `happiness_rank` vào làm biến đầu vào để gom cụm. Chúng chỉ được dùng để hậu kiểm ở Notebook 04.

In [1]:
import os
import sys
from pathlib import Path
import pandas as pd
import numpy as np

# Thiết lập đường dẫn tương đối độc lập môi trường (hỗ trợ cả VS Code và Jupyter)
current_dir = Path.cwd().resolve()
if (current_dir / 'data').exists() and (current_dir / 'src').exists():
    project_root = current_dir
elif (current_dir.parent / 'data').exists() and (current_dir.parent / 'src').exists():
    project_root = current_dir.parent
else:
    project_root = current_dir
    for parent in current_dir.parents:
        if (parent / 'data').exists() and (parent / 'src').exists():
            project_root = parent
            break

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from src.data.data_loader import (
    load_raw_data,
    load_year_data,
    standardize_columns,
    build_interim_dataset,
    INTERIM_COLUMNS,
)
print('Project root:', project_root)

Project root: C:\Users\xpaga\Documents\data_mining

## [Bước 2/11] Tìm hiểu dữ liệu (Data Understanding)
- **Nguồn dữ liệu:** Kaggle - World Happiness Report (2015 - 2019).
- **Nội dung:** Khảo sát hàng năm về chất lượng cuộc sống dựa trên thang đo Gallup World Poll (Cantril Ladder từ 0 đến 10).
- **Nhiệm vụ:** Tải và kiểm tra cấu trúc 5 tệp dữ liệu tương ứng các năm từ 2015 đến 2019.

In [2]:
raw_data = load_raw_data(raw_dir=project_root / 'data' / 'raw')
for year, df in raw_data.items():
    print(f'Năm {year}: {df.shape[0]} dòng, {df.shape[1]} cột')
    print(f'   Các cột ban đầu: {list(df.columns[:5])} ...')

Năm 2015: 158 dòng, 13 cột
   Các cột ban đầu: ['country', 'region', 'happiness_rank', 'happiness_score', 'Standard Error'] ...
Năm 2016: 157 dòng, 14 cột
   Các cột ban đầu: ['country', 'region', 'happiness_rank', 'happiness_score', 'Lower Confidence Interval'] ...
Năm 2017: 155 dòng, 13 cột
   Các cột ban đầu: ['country', 'happiness_rank', 'happiness_score', 'Whisker.high', 'Whisker.low'] ...
Năm 2018: 156 dòng, 10 cột
   Các cột ban đầu: ['happiness_rank', 'country', 'happiness_score', 'gdp_per_capita', 'social_support'] ...
Năm 2019: 156 dòng, 10 cột
   Các cột ban đầu: ['happiness_rank', 'country', 'happiness_score', 'gdp_per_capita', 'social_support'] ...

In [3]:
# Xem cấu trúc chi tiết và kiểu dữ liệu của năm 2019
raw_data[2019].info()
raw_data[2019].head()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   happiness_rank           156 non-null    int64
 1   country                  156 non-null    str
 2   happiness_score          156 non-null    float64
 3   gdp_per_capita           156 non-null    float64
 4   social_support           156 non-null    float64
 5   healthy_life_expectancy  156 non-null    float64
 6   freedom                  156 non-null    float64
 7   generosity               156 non-null    float64
 8   corruption_perception    156 non-null    float64
 9   year                     156 non-null    int64
dtypes: float64(7), int64(2), str(1)
memory usage: 13.6 KB

,happiness_rank,country,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom,generosity,corruption_perception,year
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

## [Bước 3/11] Đánh giá chất lượng dữ liệu (Data Quality Assessment)
Kiểm tra toàn diện các khía cạnh chất lượng dữ liệu qua 5 năm khảo sát (2015 - 2019):
1. **Sự bất đồng bộ cấu trúc và tên cột (Schema Inconsistency):**
   - Tên thuộc tính thay đổi liên tục qua các năm (ví dụ: `Happiness Rank` -> `Happiness.Rank` -> `Overall rank`).
   - Cột phân loại khu vực địa lý (`Region`) chỉ xuất hiện trong 2 năm đầu (2015 - 2016) và bị lược bỏ từ năm 2017 trở đi.
   - Sự hiện diện của các cột sai số đo lường khảo sát: `Standard Error` (2015), `Lower/Upper Confidence Interval` (2016), `Whisker.high/Whisker.low` (2017).
2. **Khảo sát giá trị thiếu (Missing values / NaN):**
   - Hầu hết các năm đều có dữ liệu đầy đủ cho các yếu tố cơ sở.
   - **Phát hiện ngoại lệ:** Năm 2018 bị khuyết thiếu đúng 1 giá trị tại thuộc tính `Perceptions of corruption` ở quốc gia **United Arab Emirates (UAE)**.
3. **Kiểm tra dữ liệu trùng lặp (Duplicate rows / Country names):**
   - Đảm bảo trong mỗi năm khảo sát không có quốc gia nào bị lặp lại dòng dữ liệu.

In [4]:
# 1. Đánh giá tính nhất quán của tên cột
for year, df in raw_data.items():
    print(f'\n--- Danh sách cột năm {year} sau chuẩn hóa ---')
    print(list(df.columns))

--- Danh sách cột năm 2015 sau chuẩn hóa ---
['country', 'region', 'happiness_rank', 'happiness_score', 'Standard Error', 'gdp_per_capita', 'social_support', 'healthy_life_expectancy', 'freedom', 'corruption_perception', 'generosity', 'dystopia_residual', 'year']

--- Danh sách cột năm 2016 sau chuẩn hóa ---
['country', 'region', 'happiness_rank', 'happiness_score', 'Lower Confidence Interval', 'Upper Confidence Interval', 'gdp_per_capita', 'social_support', 'healthy_life_expectancy', 'freedom', 'corruption_perception', 'generosity', 'dystopia_residual', 'year']

--- Danh sách cột năm 2017 sau chuẩn hóa ---
['country', 'happiness_rank', 'happiness_score', 'Whisker.high', 'Whisker.low', 'gdp_per_capita', 'social_support', 'healthy_life_expectancy', 'freedom', 'generosity', 'corruption_perception', 'dystopia_residual', 'year']

--- Danh sách cột năm 2018 sau chuẩn hóa ---
['happiness_rank', 'country', 'happiness_score', 'gdp_per_capita', 'social_support', 'healthy_life_expectancy', 'freedom', 'generosity', 'corruption_perception', 'year']

--- Danh sách cột năm 2019 sau chuẩn hóa ---
['happiness_rank', 'country', 'happiness_score', 'gdp_per_capita', 'social_support', 'healthy_life_expectancy', 'freedom', 'generosity', 'corruption_perception', 'year']

In [5]:
# 2. Kiểm tra giá trị thiếu (Missing values) trong từng năm
for year, df in raw_data.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    print(f'Năm {year}: {len(missing)} cột có giá trị thiếu')
    if len(missing) > 0:
        print(missing)

Năm 2015: 0 cột có giá trị thiếu
Năm 2016: 0 cột có giá trị thiếu
Năm 2017: 0 cột có giá trị thiếu
Năm 2018: 1 cột có giá trị thiếu
corruption_perception    1
dtype: int64
Năm 2019: 0 cột có giá trị thiếu

In [6]:
# 3. Kiểm tra bản ghi trùng lặp (Duplicates)
for year, df in raw_data.items():
    dup_count = df.duplicated(subset=['country']).sum()
    print(f'Năm {year}: {dup_count} quốc gia bị trùng lặp')

Năm 2015: 0 quốc gia bị trùng lặp
Năm 2016: 0 quốc gia bị trùng lặp
Năm 2017: 0 quốc gia bị trùng lặp
Năm 2018: 0 quốc gia bị trùng lặp
Năm 2019: 0 quốc gia bị trùng lặp

## [Bước 4/11 - Phần 1] Tiền xử lý dữ liệu và Xây dựng tập dữ liệu trung gian (Interim Dataset)

Để chuẩn bị dữ liệu chuẩn xác cho các bước EDA và gom cụm tiếp theo, quy trình tiền xử lý tuân thủ các nguyên tắc khoa học sau:

### 1. Cơ sở khoa học của việc loại bỏ các cột sai số đo lường mẫu
- Các cột `Standard Error` (2015), `Lower Confidence Interval`, `Upper Confidence Interval` (2016), `Whisker.high`, `Whisker.low` (2017) là các chỉ số biểu thị sai số ước lượng mẫu và khoảng tin cậy 95% của cuộc thăm dò dư luận Gallup World Poll.
- Chúng phản ánh kích thước mẫu và độ biến động thống kê trong quy trình chọn mẫu, **hoàn toàn không mang giá trị nội hàm kinh tế - xã hội** cấu thành chất lượng sống của một quốc gia.
- Nếu giữ lại các cột này, chúng sẽ làm biến dạng không gian đặc trưng, gây nhiễu ma trận khoảng cách Euclidean và dẫn tới việc gom cụm bị lệch theo độ lớn sai số khảo sát thay vì theo bản chất phát triển quốc gia. Do đó, việc loại bỏ triệt để là bắt buộc.

### 2. Xử lý mẫu khuyết thiếu: Loại bỏ ngoại lệ United Arab Emirates (UAE) năm 2018
- Qua bước đánh giá chất lượng, quan sát duy nhất bị thiếu trong toàn bộ 5 năm là UAE năm 2018 tại cột `corruption_perception` (do cuộc khảo sát không thu thập được chỉ số này tại UAE năm 2018).
- Tỷ lệ thiếu chỉ là 1 / 782 mẫu (xấp xỉ 0.128%). Việc loại bỏ mẫu này (listwise deletion) là phương án tối ưu và an toàn, vì việc điền khuyết (imputation) bằng trung bình hoặc nội suy có thể tạo ra giả định sai lệch về nhận thức thể chế tại quốc gia Trung Đông này.
- Sau khi loại bỏ UAE 2018, tập dữ liệu còn lại chính xác **781 dòng**, bảo đảm 100% sạch (0 missing values trên 6 biến cơ sở).

### 3. Nguyên tắc bảo toàn bất biến của bài toán Gom cụm (Đề tài 16)
- **Ma trận đặc trưng gom cụm ($X$):** Tuyệt đối chỉ sử dụng 6 thuộc tính cơ sở:
  1. `gdp_per_capita` (Kinh tế)
  2. `social_support` (Hỗ trợ xã hội)
  3. `healthy_life_expectancy` (Tuổi thọ và sức khỏe)
  4. `freedom` (Tự do lựa chọn cuộc sống)
  5. `generosity` (Hào phóng / đóng góp cộng đồng)
  6. `corruption_perception` (Nhận thức tham nhũng / niềm tin thể chế)
- **Biến mục tiêu đối sánh:** `happiness_score` và `happiness_rank` được lưu trong bảng trung gian để đối chiếu, hậu kiểm ở Bước 9 (Notebook 04), tuyệt đối **không tham gia vào quá trình tính khoảng cách hay huấn luyện cụm**.

### 4. Bổ sung thông tin chuẩn hóa
- Điền khuyết cột `region` cho giai đoạn 2017-2019 dựa trên bảng tham chiếu 2015-2016 và ánh xạ địa lý.
- Bổ sung mã quốc tế `iso_alpha` (ISO 3166-1 alpha-3) cho tất cả các quốc gia để phục vụ trực quan hóa bản đồ không gian và ứng dụng tương tác.
- Giữ đúng cấu trúc 13 cột chuẩn theo `INTERIM_COLUMNS` và ghi ra tệp `data/interim/happiness_merged.csv`.

In [7]:
interim_path = project_root / 'data' / 'interim' / 'happiness_merged.csv'
interim_df = build_interim_dataset(
    years=[2015, 2016, 2017, 2018, 2019],
    raw_dir=project_root / 'data' / 'raw',
    output_path=interim_path,
)

print(f'Đã sinh bảng dữ liệu trung gian chuẩn: {interim_df.shape} tại {interim_path}')
print('\nKiểm tra thông tin dữ liệu (interim_df.info()):')
interim_df.info()

print('\nKiểm tra số lượng giá trị thiếu trên từng cột:')
print(interim_df.isnull().sum())

core_features = [
    'gdp_per_capita',
    'social_support',
    'healthy_life_expectancy',
    'freedom',
    'corruption_perception',
    'generosity',
]
print(f'\nTổng số giá trị thiếu trong 6 thuộc tính cơ sở: {interim_df[core_features].isna().sum().sum()}')

uae_2018 = interim_df[(interim_df['year'] == 2018) & (interim_df['country'] == 'United Arab Emirates')]
print(f'Kiểm tra UAE 2018 tồn tại trong dữ liệu (kỳ vọng: 0 dòng): {len(uae_2018)} dòng')

display(interim_df.head())

Đã sinh bảng dữ liệu trung gian chuẩn: (781, 13) tại C:\Users\xpaga\Documents\data_mining\data\interim\happiness_merged.csv

Kiểm tra thông tin dữ liệu (interim_df.info()):
<class 'pandas.DataFrame'>
Index: 781 entries, 0 to 781
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  781 non-null    str
 1   region                   781 non-null    str
 2   happiness_rank           781 non-null    int64
 3   happiness_score          781 non-null    float64
 4   gdp_per_capita           781 non-null    float64
 5   social_support           781 non-null    float64
 6   healthy_life_expectancy  781 non-null    float64
 7   freedom                  781 non-null    float64
 8   corruption_perception    781 non-null    float64
 9   generosity               781 non-null    float64
 10  dystopia_residual        781 non-null    float64
 11  year                     781 non-null    int64
 12  iso_alpha                781 non-null    str
dtypes: float64(8), int64(2), str(3)
memory usage: 110.3 KB

Kiểm tra số lượng giá trị thiếu trên từng cột:
country                    0
region                     0
happiness_rank             0
happiness_score            0
gdp_per_capita             0
social_support             0
healthy_life_expectancy    0
freedom                    0
corruption_perception      0
generosity                 0
dystopia_residual          0
year                       0
iso_alpha                  0
dtype: int64

Tổng số giá trị thiếu trong 6 thuộc tính cơ sở: 0
Kiểm tra UAE 2018 tồn tại trong dữ liệu (kỳ vọng: 0 dòng): 0 dòng

,country,region,happiness_rank,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom,corruption_perception,generosity,dystopia_residual,year,iso_alpha
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,CHE
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,ISL
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,DNK
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NOR
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,CAN